### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] unable to get local issuer certificate running build.py

### ISSUE THREAD

**Issue by Facsimiler** [lancaster-university/codal-bootstrap#5]
I'm getting an error stating that an SSL certificate cannot be validated upon running `.\build.py`:

I'm running this on macOS V13.2, with python V3.10.9

Am I missing a python package? Something else? (`pip3 list` lists only pip itself, V23.0).

```plain
Downloading codal-bootstrap...
Cloning into '/Users/me/src/MyProject/libraries/codal-bootstrap'...
remote: Enumerating objects: 280, done.
remote: Counting objects: 100% (280/280), done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 280 (delta 151), reused 218 (delta 93), pack-reused 0
Receiving objects: 100% (280/280), 71.75 KiB | 536.00 KiB/s, done.
Resolving deltas: 100% (151/151), done.
Please supply an initial target to build against:
Downloading valid targets...
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/src/MyProject/./build.py", line 51, in <module>
    bootstrap.go_bootstrap( TARGET_LIST )
  File "/Users/me/src/MyProject/libraries/codal-bootstrap/bootstrap.py", line 285, in go_bootstrap
    list_valid_targets( target_list )
  File "/Users/me/src/MyProject/libraries/codal-bootstrap/bootstrap.py", line 155, in list_valid_targets
    targets = download_targets( target_list )
  File "/Users/me/src/MyProject/libraries/codal-bootstrap/bootstrap.py", line 78, in download_targets
    r = urllib.request.urlopen( url )
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by JohnVidler** [comment]
That looks like its trying to download the target list but https connections are failing... strange. Can you verify that running the following give you a JSON list of targets please?

`curl https://raw.githubusercontent.com/lancaster-university/codal/master/utils/targets.json`

If that doesn't work, it might be that your system certificates for SSL aren't up to date, although I'm not entirely sure how that would happen!

Let me know how the above goes, and we can investigate further

**Comment by JohnVidler** [comment]
Just as a sanity check, I set up a fresh project on my Mac (currently on 13.1) and it seems to be behaving, so I'm suspicious that its something system-y going on: https://asciinema.org/a/xBeiuEziEx0wxsWul8PGI3uC3

Can you additionally run the following and let me know what you get? Hopefully it'll let me see what's going on with your setup

```
python3 --version

pip3 --version

which python3

./build.py --help
```

**Comment by Facsimiler** [comment]
Hi @JohnVidler. Thanks for the quick reply.

I was able to execute the `curl` command without a problem.

Here's the output from the commands:

`python3 --version`:
```plain
Python 3.10.9
```

`pip3 --version`:
```plain
pip 23.0 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
```

`which python3`:
```plain
/opt/homebrew/bin/python3
```

`./build.py`:
```plain
Usage: build.py target-name [options]

BOOTSTRAP MODE - Configures the current project directory for a specified
target. Will defer to the latest build tools once configured.

Options:
  -h, --help            show this help message and exit
  --bootstrap           Skips any already downloaded build toolchain, and runs
                        in bootstrap mode directly.
  --ignore-codal        Skips any pre-existing codal.json in the project
                        folder, and runs as if none exists.
  --merge-upstream-target
                        Keeps the existing codal.json, but only for non-target
                        parameters, merging the new target definition in with
                        the old arguments.
  --makedocs            Builds documentation (including supported libraries)
                        with doxygen
  -u                    Update this file and the build tools library
```

I Googled the error a file and found what is possibly a relevant `StackOverflow` question: https://stackoverflow.com/q/56587204/2593574

Homebrew installed `openssl@1.1` as a dependency of `python@3.10`, and that might be the explanation. I'll experiment with newer versions of that library...

**Comment by Facsimiler** [comment]
It seems that the version of python I installed using homebrew was the cause of this issue, with its dependency upon openssl@1.1. I uninstalled that version of python, and everything works OK. Apologies for the false alarm...

**Comment by JohnVidler** [comment]
No problem! Sorry I didn't reply to this sooner, I had a week of flu :)
